package hotkeys

// DefaultMainBindings returns main-window shortcuts for Phase 1.
func DefaultMainBindings() []Binding {
	return []Binding{
		{Key: "F1", Command: "cm_HelpIndex"},
		{Key: "F2", Command: "cm_RenameOnly"},
		{Key: "Shift+F6", Command: "cm_RenameOnly"},
		{Key: "F3", Command: "cm_View"},
		{Key: "F4", Command: "cm_Edit"},
		{Key: "F5", Command: "cm_Copy"},
		{Key: "F6", Command: "cm_Rename"},
		{Key: "F7", Command: "cm_MakeDir"},
		{Key: "F8", Command: "cm_Delete"},
		{Key: "Del", Command: "cm_Delete"},
		{Key: "Shift+F8", Command: "cm_Delete", Params: []string{"trashcan=reversesetting"}},
		{Key: "Shift+Del", Command: "cm_Delete", Params: []string{"trashcan=reversesetting"}},
		{Key: "Alt+F1", Command: "cm_LeftOpenDrives"},
		{Key: "Alt+F2", Command: "cm_RightOpenDrives"},
		{Key: "Alt+F4", Command: "cm_Exit"},
		{Key: "Alt+X", Command: "cm_Exit"},
		{Key: "Ctrl+F1", Command: "cm_BriefView"},
		{Key: "Ctrl+F2", Command: "cm_ColumnsView"},
		{Key: "Ctrl+F3", Command: "cm_SortByName"},
		{Key: "Ctrl+F4", Command: "cm_SortByExt"},
		{Key: "Ctrl+F5", Command: "cm_SortByDate"},
		{Key: "Ctrl+F6", Command: "cm_SortBySize"},
		{Key: "Ctrl+H", Command: "cm_ShowSysFiles"},
		{Key: "Ctrl+L", Command: "cm_FocusCmdLine"},
		{Key: "Ctrl+S", Command: "cm_QuickFilter"},
		{Key: "Ctrl+Q", Command: "cm_QuickView"},
		{Key: "Ctrl+T", Command: "cm_NewTab"},
		{Key: "Ctrl+W", Command: "cm_CloseTab"},
		{Key: "Ctrl+Tab", Command: "cm_NextTab"},
		{Key: "Ctrl+Shift+Tab", Command: "cm_PrevTab"},
		{Key: "Ctrl+B", Command: "cm_FlatView"},
		{Key: "Ctrl+Shift+B", Command: "cm_FlatViewSel"},
		{Key: "Ctrl+C", Command: "cm_CopyFullNamesToClip"},
		{Key: "Ctrl+X", Command: "cm_CutToClipboard"},
		{Key: "Ctrl+V", Command: "cm_PasteFromClipboard"},
		{Key: "Alt+Down", Command: "cm_DirHistory"},
		{Key: "Alt+Left", Command: "cm_ViewHistoryPrev"},
		{Key: "Alt+Right", Command: "cm_ViewHistoryNext"},
		{Key: "Alt+F8", Command: "cm_ShowCmdLineHistory"},
		{Key: "Ctrl+Down", Command: "cm_ShowCmdLineHistory"},
		{Key: "Ctrl+R", Command: "cm_Refresh"},
		{Key: "Ctrl+U", Command: "cm_Exchange"},
		{Key: "\\", Command: "cm_TransferPath"},
		{Key: "Ctrl+\\", Command: "cm_TransferPath"},
		{Key: "Ctrl+A", Command: "cm_SelectAll"},
		{Key: "Ctrl+Left", Command: "cm_ChangeDirToRoot"},
		{Key: "Ctrl+Right", Command: "cm_ChangeDirToHome"},
		{Key: "Tab", Command: "cm_SwitchPnl"},
		{Key: "Enter", Command: "cm_Open"},
		{Key: "Insert", Command: "cm_Select"},
		{Key: "Backspace", Command: "cm_ChangeDirToParent"},
		{Key: "Space", Command: "cm_CalculateSpace"},
		{Key: "Up", Command: "cm_MoveUp"},
		{Key: "Down", Command: "cm_MoveDown"},
		{Key: "*", Command: "cm_InvertSelection"},
	}
}
